---
output: github_document
bibliography: biblio.bib
csl: apa.csl
---

<!-- Este .md fue generado a partir del .Rmd homónimo. Edítese el .Rmd -->

# Contexto físico: la "plantilla" geográfica

La idea es que uses las referencias para "intentar" aprender sobre qué condicionamientos físicos actúan en la distribución de especies.

Tus referencias serán los capítulos 3 a 5 de @smith2007ecologia y el capítulo 3 de @lomolino2006biogeography. Alternativamente, puedes consultar la versión resumida de este tema que se encuentra en [este vídeo de YouTube](https://www.youtube.com/watch?v=R8m_EmZsxJU), así como en [esta presentación de diapositivas](https://drive.google.com/file/d/1-3os3Y9b6V2IkPhMUTYtbvIQag7dfeIL/view?usp=sharing).

## Preguntas/mandatos. Responde según las referencias señaladas arriba. En caso de que prefieras usar otras referencias, indícalas.

* ¿Cuáles son las principales variables climáticas que determinan la distribución de la vegetación terrestre?

    Tu respuesta, aquí: ...

* Si 100 unidades de radiación solar alcanzan el tope de la atmósfera, ¿Por qué el planeta emite 147 unidades?

    Tu respuesta, aquí: ...
    


* En cuanto a emisividad, la Tierra y el Sol se comportan como cuerpos negros, ¿Por qué?

    Tu respuesta, aquí: ...
    
* Cada quien tiene asignado un valor de temperatura de cuerpo negro en grados Kelvin. Usa el recuadro "Cuantificando la ecología 3.1" de @smith2007ecologia. ¿Cuánta energía radiante emite el cuerpo?

    ```{r, echo=F}
    source('temp_aleatorias.R')
    temp()
    ```

    Tu respuesta, aquí: ...
    
* Usando el mismo recuadro y el mismo valor de temperatura, ¿En qué longitud de onda emite dicho cuerpo más radiación electromagnética?
    
    Tu respuesta, aquí: ...

* ¿En dos palabras, que es la PAR?

    Tu respuesta, aquí: ...

* Define el espectro electromagnético, pero con tus propias palabras.

    Tu respuesta, aquí: ...
    
* Explica el mecanismo, con tus palabras y sin pasar de la columna 200, ¿Por qué la radiación solar interceptada varía según las estaciones?

# Referencias
